using Microsoft.Extensions.DependencyInjection;
using OrderHub.Application.Abstractions.Commands;
using OrderHub.Application.Abstractions.Queries;
using OrderHub.Application.Dispatching;
using OrderHub.Application.Tenancy;
using OrderHub.Application.Tenancy.CreateEstablishment;
using FluentValidation;
using OrderHub.Application.Identity.CreateAdministrativeUser;
using OrderHub.Application.Abstractions.Catalog;
using OrderHub.Application.Catalog;
using OrderHub.Application.Abstractions.Customers;
using OrderHub.Application.Customers;
using OrderHub.Application.Abstractions.Ordering;
using OrderHub.Application.Ordering;
using OrderHub.Application.Abstractions.Promotions;
using OrderHub.Application.Promotions;
using OrderHub.Application.Abstractions.Payments;
using OrderHub.Application.Payments;
using OrderHub.Application.Abstractions.PublicOrdering;
using OrderHub.Application.PublicOrdering;
using OrderHub.Application.Identity.Authentication;
using OrderHub.Application.Identity.Management;

namespace OrderHub.Application;

public static class DependencyInjection
{
    public static IServiceCollection AddApplication(this IServiceCollection services)
    {
        services.AddScoped<ICommandDispatcher, CommandDispatcher>();
        services.AddScoped<IQueryDispatcher, QueryDispatcher>();
        services.AddScoped<EstablishmentScopeResolver>();
        services.AddScoped<AdministrativeUserManagement>();
        services.AddScoped<IQueryHandler<SearchAdministrativeUsersQuery, AdministrativeUserSearchResult>, SearchAdministrativeUsersQueryHandler>();
        services.AddScoped<IValidator<SearchAdministrativeUsersQuery>, SearchAdministrativeUsersQueryValidator>();
        services.AddScoped<ICommandHandler<UpdateAdministrativeUserCommand>, UpdateAdministrativeUserCommandHandler>();
        services.AddScoped<IValidator<UpdateAdministrativeUserCommand>, UpdateAdministrativeUserCommandValidator>();
        services.AddScoped<ICommandHandler<SetAdministrativeUserActiveCommand>, SetAdministrativeUserActiveCommandHandler>();
        services.AddScoped<IValidator<SetAdministrativeUserActiveCommand>, SetAdministrativeUserActiveCommandValidator>();
        services.AddScoped<ICommandHandler<SetAdministrativeUserRoleCommand>, SetAdministrativeUserRoleCommandHandler>();
        services.AddScoped<IValidator<SetAdministrativeUserRoleCommand>, SetAdministrativeUserRoleCommandValidator>();
        services.AddScoped<ICommandHandler<SetAdministrativeUserAccessCommand>, SetAdministrativeUserAccessCommandHandler>();
        services.AddScoped<IValidator<SetAdministrativeUserAccessCommand>, SetAdministrativeUserAccessCommandValidator>();
        services.AddSingleton(TimeProvider.System);
        services.AddScoped<ICommandHandler<CreateEstablishmentCommand, Guid>, CreateEstablishmentCommandHandler>();
        services.AddScoped<IValidator<CreateEstablishmentCommand>, CreateEstablishmentCommandValidator>();
        services.AddScoped<ICommandHandler<CreateAdministrativeUserCommand, Guid>, CreateAdministrativeUserCommandHandler>();
        services.AddScoped<IValidator<CreateAdministrativeUserCommand>, CreateAdministrativeUserCommandValidator>();
        services.AddScoped<ICommandHandler<BeginAuthenticationCommand, AuthenticationChallengeResult>, BeginAuthenticationCommandHandler>();
        services.AddScoped<IQueryHandler<GetAuthenticationContextQuery, AuthenticationContext>, GetAuthenticationContextQueryHandler>();
        services.AddScoped<ICommandHandler<CompleteAuthenticationCommand, AuthenticationTokens>, CompleteAuthenticationCommandHandler>();
        services.AddScoped<ICommandHandler<RefreshAuthenticationCommand, AuthenticationTokens>, RefreshAuthenticationCommandHandler>();
        services.AddScoped<ICommandHandler<LogoutCommand>, LogoutCommandHandler>();
        services.AddScoped<ICommandHandler<ChangeTemporaryPasswordCommand>, ChangeTemporaryPasswordCommandHandler>();
        services.AddScoped<ICommandHandler<CreatePlatformUserCommand, Guid>, CreatePlatformUserCommandHandler>();
        services.AddScoped<ICommandHandler<SetPlatformUserActiveCommand>, SetPlatformUserActiveCommandHandler>();
        services.AddScoped<IValidator<BeginAuthenticationCommand>, BeginAuthenticationCommandValidator>();
        services.AddScoped<IValidator<CompleteAuthenticationCommand>, CompleteAuthenticationCommandValidator>();
        services.AddScoped<IValidator<ChangeTemporaryPasswordCommand>, ChangeTemporaryPasswordCommandValidator>();
        services.AddScoped<ICommandHandler<UpsertCategoryCommand, Guid>, UpsertCategoryCommandHandler>();
        services.AddScoped<ICommandHandler<UpsertProductCommand, Guid>, UpsertProductCommandHandler>();
        services.AddScoped<ICommandHandler<UpsertAdditionalCommand, Guid>, UpsertAdditionalCommandHandler>();
        services.AddScoped<ICommandHandler<UpsertAdditionalGroupCommand, Guid>, UpsertAdditionalGroupCommandHandler>();
        services.AddScoped<IQueryHandler<GetAdministrativeCatalogQuery, CatalogReadModel>, GetAdministrativeCatalogQueryHandler>();
        services.AddScoped<IQueryHandler<SearchAdditionalsQuery, AdditionalSearchResult>, SearchAdditionalsQueryHandler>();
        services.AddScoped<IQueryHandler<SearchAdditionalGroupsQuery, AdditionalGroupSearchResult>, SearchAdditionalGroupsQueryHandler>();
        services.AddScoped<IValidator<SearchAdditionalsQuery>, SearchAdditionalsQueryValidator>();
        services.AddScoped<IValidator<SearchAdditionalGroupsQuery>, SearchAdditionalGroupsQueryValidator>();
        services.AddScoped<IQueryHandler<GetPublicCatalogQuery, CatalogReadModel>, GetPublicCatalogQueryHandler>();
        services.AddScoped<IValidator<UpsertCategoryCommand>, UpsertCategoryCommandValidator>();
        services.AddScoped<IValidator<UpsertProductCommand>, UpsertProductCommandValidator>();
        services.AddScoped<IValidator<UpsertAdditionalCommand>, UpsertAdditionalCommandValidator>();
        services.AddScoped<IValidator<UpsertAdditionalGroupCommand>, UpsertAdditionalGroupCommandValidator>();
        services.AddScoped<IValidator<GetAdministrativeCatalogQuery>, GetAdministrativeCatalogQueryValidator>();
        services.AddScoped<IValidator<GetPublicCatalogQuery>, GetPublicCatalogQueryValidator>();
        services.AddScoped<ICommandHandler<UpsertCustomerCommand, Guid>, UpsertCustomerCommandHandler>();
        services.AddScoped<ICommandHandler<UpsertCustomerAddressCommand, Guid>, UpsertCustomerAddressCommandHandler>();
        services.AddScoped<ICommandHandler<RemoveCustomerAddressCommand>, RemoveCustomerAddressCommandHandler>();
        services.AddScoped<IQueryHandler<SearchCustomersQuery, CustomerSearchResult>, SearchCustomersQueryHandler>();
        services.AddScoped<IValidator<UpsertCustomerCommand>, UpsertCustomerCommandValidator>();
        services.AddScoped<IValidator<UpsertCustomerAddressCommand>, UpsertCustomerAddressCommandValidator>();
        services.AddScoped<IValidator<RemoveCustomerAddressCommand>, RemoveCustomerAddressCommandValidator>();
        services.AddScoped<IValidator<SearchCustomersQuery>, SearchCustomersQueryValidator>();
        services.AddScoped<ICommandHandler<CreateOrderDraftCommand, Guid>, CreateOrderDraftCommandHandler>();
        services.AddScoped<ICommandHandler<AddOrderItemCommand, Guid>, AddOrderItemCommandHandler>();
        services.AddScoped<ICommandHandler<ConfirmOrderCommand>, ConfirmOrderCommandHandler>();
        services.AddScoped<ICommandHandler<TransitionOrderCommand>, TransitionOrderCommandHandler>();
        services.AddScoped<IQueryHandler<GetOrderQuery, OrderReadModel>, GetOrderQueryHandler>();
        services.AddScoped<IQueryHandler<SearchOrdersQuery, OrderSearchResult>, SearchOrdersQueryHandler>();
        services.AddScoped<IValidator<CreateOrderDraftCommand>, CreateOrderDraftCommandValidator>();
        services.AddScoped<IValidator<AddOrderItemCommand>, AddOrderItemCommandValidator>();
        services.AddScoped<IValidator<ConfirmOrderCommand>, ConfirmOrderCommandValidator>();
        services.AddScoped<IValidator<TransitionOrderCommand>, TransitionOrderCommandValidator>();
        services.AddScoped<IValidator<GetOrderQuery>, GetOrderQueryValidator>();
        services.AddScoped<IValidator<SearchOrdersQuery>, SearchOrdersQueryValidator>();
        services.AddScoped<ICommandHandler<UpsertCouponCommand, Guid>, UpsertCouponCommandHandler>();
        services.AddScoped<ICommandHandler<SetCouponActiveCommand>, SetCouponActiveCommandHandler>();
        services.AddScoped<ICommandHandler<ApplyCouponCommand>, ApplyCouponCommandHandler>();
        services.AddScoped<ICommandHandler<RemoveCouponCommand>, RemoveCouponCommandHandler>();
        services.AddScoped<IQueryHandler<ListCouponsQuery, IReadOnlyList<CouponReadModel>>, ListCouponsQueryHandler>();
        services.AddScoped<IQueryHandler<SearchCouponsQuery, CouponSearchResult>, SearchCouponsQueryHandler>();
        services.AddScoped<IValidator<UpsertCouponCommand>, UpsertCouponCommandValidator>();
        services.AddScoped<IValidator<SetCouponActiveCommand>, SetCouponActiveCommandValidator>();
        services.AddScoped<IValidator<ApplyCouponCommand>, ApplyCouponCommandValidator>();
        services.AddScoped<IValidator<RemoveCouponCommand>, RemoveCouponCommandValidator>();
        services.AddScoped<IValidator<ListCouponsQuery>, ListCouponsQueryValidator>();
        services.AddScoped<IValidator<SearchCouponsQuery>, SearchCouponsQueryValidator>();
        services.AddScoped<ICommandHandler<UpsertPaymentMethodCommand, Guid>, UpsertPaymentMethodCommandHandler>();
        services.AddScoped<ICommandHandler<SetPaymentMethodActiveCommand>, SetPaymentMethodActiveCommandHandler>();
        services.AddScoped<ICommandHandler<CreatePaymentCommand, Guid>, CreatePaymentCommandHandler>();
        services.AddScoped<ICommandHandler<ConfirmPaymentCommand, Guid>, ConfirmPaymentCommandHandler>();
        services.AddScoped<ICommandHandler<FailPaymentCommand>, FailPaymentCommandHandler>();
        services.AddScoped<ICommandHandler<CancelPaymentCommand>, CancelPaymentCommandHandler>();
        services.AddScoped<IQueryHandler<ListPaymentMethodsQuery, IReadOnlyList<PaymentMethodReadModel>>, ListPaymentMethodsQueryHandler>();
        services.AddScoped<IQueryHandler<GetOrderPaymentsQuery, OrderPaymentsReadModel>, GetOrderPaymentsQueryHandler>();
        services.AddScoped<IQueryHandler<SearchPaymentMethodsQuery, PaymentMethodSearchResult>, SearchPaymentMethodsQueryHandler>();
        services.AddScoped<IValidator<UpsertPaymentMethodCommand>, UpsertPaymentMethodCommandValidator>();
        services.AddScoped<IValidator<SetPaymentMethodActiveCommand>, SetPaymentMethodActiveCommandValidator>();
        services.AddScoped<IValidator<CreatePaymentCommand>, CreatePaymentCommandValidator>();
        services.AddScoped<IValidator<ConfirmPaymentCommand>, ConfirmPaymentCommandValidator>();
        services.AddScoped<IValidator<FailPaymentCommand>, FailPaymentCommandValidator>();
        services.AddScoped<IValidator<CancelPaymentCommand>, CancelPaymentCommandValidator>();
        services.AddScoped<IValidator<ListPaymentMethodsQuery>, ListPaymentMethodsQueryValidator>();
        services.AddScoped<IValidator<GetOrderPaymentsQuery>, GetOrderPaymentsQueryValidator>();
        services.AddScoped<IValidator<SearchPaymentMethodsQuery>, SearchPaymentMethodsQueryValidator>();
        services.AddScoped<IQueryHandler<GetPublicContextQuery, PublicOrderingContext>, GetPublicContextQueryHandler>();
        services.AddScoped<ICommandHandler<UpsertPublicCustomerCommand, PublicCustomerResult>, UpsertPublicCustomerCommandHandler>();
        services.AddScoped<IQueryHandler<SimulatePublicOrderQuery, PublicSimulation>, SimulatePublicOrderQueryHandler>();
        services.AddScoped<ICommandHandler<ConfirmPublicOrderCommand, PublicConfirmation>, ConfirmPublicOrderCommandHandler>();
        services.AddScoped<IQueryHandler<GetPublicOrderQuery, OrderReadModel>, GetPublicOrderQueryHandler>();
        services.AddScoped<ICommandHandler<CancelPublicOrderCommand>, CancelPublicOrderCommandHandler>();
        services.AddScoped<IValidator<GetPublicContextQuery>, GetPublicContextQueryValidator>();
        services.AddScoped<IValidator<UpsertPublicCustomerCommand>, UpsertPublicCustomerCommandValidator>();
        services.AddScoped<IValidator<SimulatePublicOrderQuery>, SimulatePublicOrderQueryValidator>();
        services.AddScoped<IValidator<ConfirmPublicOrderCommand>, ConfirmPublicOrderCommandValidator>();
        services.AddScoped<IValidator<GetPublicOrderQuery>, GetPublicOrderQueryValidator>();
        services.AddScoped<IValidator<CancelPublicOrderCommand>, CancelPublicOrderCommandValidator>();
        return services;
    }
}
