// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderHub.Infrastructure.Persistence.Write;

#nullable disable

namespace OrderHub.Infrastructure.Migrations.Migrations
{
    [DbContext(typeof(OrderHubDbContext))]
    [Migration("20260820120132_IdentityOperations")]
    partial class IdentityOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderHub.Domain.Identity.AdministrativeUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastAccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_access_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_administrative_user_tenant_email");

                    b.ToTable("administrative_user", "identity");
                });

            modelBuilder.Entity("OrderHub.Domain.Operations.BusinessHours", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly>("ClosesAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("closes_at");

                    b.Property<short>("DayOfWeek")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_week");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<TimeOnly>("OpensAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("opens_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("EstablishmentId", "DayOfWeek");

                    b.HasIndex("TenantId", "EstablishmentId");

                    b.ToTable("business_hours", "operations", t =>
                        {
                            t.HasCheckConstraint("ck_business_hours_interval", "closes_at > opens_at");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Operations.ServiceTable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("QrCodeToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("qr_code_token");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("QrCodeToken")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("EstablishmentId", "Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "EstablishmentId");

                    b.ToTable("service_table", "operations");
                });

            modelBuilder.Entity("OrderHub.Domain.Tenancy.Establishment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("trade_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_establishment");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_establishment_slug");

                    b.HasIndex("TenantId");

                    b.ToTable("establishment", "tenancy");
                });

            modelBuilder.Entity("OrderHub.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.ToTable("tenant", "tenancy");
                });

            modelBuilder.Entity("OrderHub.Infrastructure.Persistence.Write.Configurations.AdministrativeRoleDefinition", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("administrative_role", "identity");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "OWNER",
                            Name = "Owner"
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "ADMIN",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "MANAGER",
                            Name = "Manager"
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "ATTENDANT",
                            Name = "Attendant"
                        },
                        new
                        {
                            Id = (short)5,
                            Code = "KITCHEN",
                            Name = "Kitchen"
                        },
                        new
                        {
                            Id = (short)6,
                            Code = "DELIVERY",
                            Name = "Delivery"
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Identity.AdministrativeUser", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("OrderHub.Domain.Identity.AdministrativeUserRole", "RoleMemberships", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<short>("Role")
                                .HasColumnType("smallint")
                                .HasColumnName("role_id");

                            b1.HasKey("UserId", "Role");

                            b1.HasIndex("Role");

                            b1.ToTable("administrative_user_role", "identity");

                            b1.HasOne("OrderHub.Infrastructure.Persistence.Write.Configurations.AdministrativeRoleDefinition", null)
                                .WithMany()
                                .HasForeignKey("Role")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("OrderHub.Domain.Identity.UserEstablishmentAccess", "EstablishmentAccesses", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<Guid>("EstablishmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("establishment_id");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean")
                                .HasColumnName("is_active");

                            b1.Property<DateTimeOffset?>("RevokedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("revoked_at");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.HasKey("UserId", "EstablishmentId");

                            b1.HasIndex("TenantId", "EstablishmentId");

                            b1.HasIndex("TenantId", "UserId");

                            b1.ToTable("user_establishment_access", "identity");

                            b1.HasOne("OrderHub.Domain.Tenancy.Establishment", null)
                                .WithMany()
                                .HasForeignKey("TenantId", "EstablishmentId")
                                .HasPrincipalKey("TenantId", "Id")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("TenantId", "UserId")
                                .HasPrincipalKey("TenantId", "Id");
                        });

                    b.Navigation("EstablishmentAccesses");

                    b.Navigation("RoleMemberships");
                });

            modelBuilder.Entity("OrderHub.Domain.Operations.BusinessHours", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Establishment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Operations.ServiceTable", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Establishment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Tenancy.Establishment", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("OrderHub.Domain.Tenancy.EstablishmentTheme", "Theme", b1 =>
                        {
                            b1.Property<Guid>("establishment_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("BackgroundColor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("background_color");

                            b1.Property<string>("FaviconUrl")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("favicon_url");

                            b1.Property<string>("FontFamily")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("font_family");

                            b1.Property<string>("LogoUrl")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("logo_url");

                            b1.Property<string>("PrimaryColor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("primary_color");

                            b1.Property<string>("SecondaryColor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("secondary_color");

                            b1.Property<string>("TextColor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("text_color");

                            b1.HasKey("establishment_id");

                            b1.ToTable("establishment_theme", "tenancy");

                            b1.WithOwner()
                                .HasForeignKey("establishment_id");
                        });

                    b.Navigation("Theme")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
