// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderHub.Infrastructure.Persistence.Write;

#nullable disable

namespace OrderHub.Infrastructure.Migrations.Migrations
{
    [DbContext(typeof(OrderHubDbContext))]
    [Migration("20260902235922_OrderPayments")]
    partial class OrderPayments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderHub.Domain.Catalog.Additional", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EstablishmentId", "Name");

                    b.ToTable("additional", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_additional_price", "price >= 0");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.AdditionalGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MaximumSelection")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_selection");

                    b.Property<int>("MinimumSelection")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_selection");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EstablishmentId", "Name");

                    b.ToTable("additional_group", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_additional_group_maximum", "maximum_selection >= 1");

                            t.HasCheckConstraint("ck_additional_group_minimum", "minimum_selection >= 0");

                            t.HasCheckConstraint("ck_additional_group_range", "minimum_selection <= maximum_selection");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.AdditionalGroupItem", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("AdditionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("additional_id");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("GroupId", "AdditionalId");

                    b.HasIndex("GroupId", "Order");

                    b.HasIndex("TenantId", "EstablishmentId", "AdditionalId");

                    b.HasIndex("TenantId", "EstablishmentId", "GroupId");

                    b.ToTable("additional_group_item", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_additional_group_item_order", "\"order\" >= 0");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EstablishmentId", "ParentCategoryId", "Order");

                    b.ToTable("category", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_category_order", "\"order\" >= 0");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowsNotes")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_notes");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("base_price");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EstablishmentId", "CategoryId");

                    b.HasIndex("TenantId", "EstablishmentId", "Code")
                        .IsUnique();

                    b.ToTable("product", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_product_base_price", "base_price >= 0");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.ProductAdditionalGroup", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("ProductId", "GroupId");

                    b.HasIndex("ProductId", "Order");

                    b.HasIndex("TenantId", "EstablishmentId", "GroupId");

                    b.HasIndex("TenantId", "EstablishmentId", "ProductId");

                    b.ToTable("product_additional_group", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_product_additional_group_order", "\"order\" >= 0");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_principal");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasFilter("is_principal");

                    b.HasIndex("ProductId", "Order");

                    b.ToTable("product_image", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_product_image_order", "\"order\" >= 0");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.ProductVariation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Order");

                    b.ToTable("product_variation", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_product_variation_order", "\"order\" >= 0");

                            t.HasCheckConstraint("ck_product_variation_price", "price >= 0");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("normalized_phone");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EstablishmentId", "NormalizedEmail");

                    b.HasIndex("TenantId", "EstablishmentId", "NormalizedPhone")
                        .IsUnique();

                    b.ToTable("customer", "customers");
                });

            modelBuilder.Entity("OrderHub.Domain.Customers.CustomerAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Complement")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("complement");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("neighborhood");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("number");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("postal_code");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("street");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "EstablishmentId", "Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EstablishmentId", "CustomerId")
                        .IsUnique()
                        .HasFilter("is_primary");

                    b.ToTable("customer_address", "customers");
                });

            modelBuilder.Entity("OrderHub.Domain.Identity.AdministrativeUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastAccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_access_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_administrative_user_tenant_email");

                    b.ToTable("administrative_user", "identity");
                });

            modelBuilder.Entity("OrderHub.Domain.Operations.BusinessHours", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly>("ClosesAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("closes_at");

                    b.Property<short>("DayOfWeek")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_week");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<TimeOnly>("OpensAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("opens_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("EstablishmentId", "DayOfWeek");

                    b.HasIndex("TenantId", "EstablishmentId");

                    b.ToTable("business_hours", "operations", t =>
                        {
                            t.HasCheckConstraint("ck_business_hours_interval", "closes_at > opens_at");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Operations.ServiceTable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("QrCodeToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("qr_code_token");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("QrCodeToken")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("EstablishmentId", "Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "EstablishmentId");

                    b.ToTable("service_table", "operations");
                });

            modelBuilder.Entity("OrderHub.Domain.Ordering.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CouponCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("coupon_code");

                    b.Property<Guid?>("CouponId")
                        .HasColumnType("uuid")
                        .HasColumnName("coupon_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("customer_phone");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discount");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<decimal>("Fees")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("fees");

                    b.Property<long?>("Number")
                        .HasColumnType("bigint")
                        .HasColumnName("number");

                    b.Property<string>("PublicReference")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("public_reference");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("service_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<Guid?>("TableId")
                        .HasColumnType("uuid")
                        .HasColumnName("table_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("PublicReference")
                        .IsUnique()
                        .HasFilter("public_reference is not null");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EstablishmentId", "CouponId");

                    b.HasIndex("TenantId", "EstablishmentId", "Number")
                        .IsUnique()
                        .HasFilter("number is not null");

                    b.ToTable("order", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_order_number", "number is null or number > 0");

                            t.HasCheckConstraint("ck_order_totals", "subtotal >= 0 and discount >= 0 and fees >= 0 and total >= 0");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Ordering.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("product_name");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<Guid?>("VariationId")
                        .HasColumnType("uuid")
                        .HasColumnName("variation_id");

                    b.Property<string>("VariationName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("variation_name");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EstablishmentId", "OrderId");

                    b.ToTable("order_item", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_order_item_values", "unit_price >= 0 and quantity > 0 and total >= 0");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Ordering.OrderItemAdditional", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdditionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("additional_id");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EstablishmentId", "OrderItemId");

                    b.ToTable("order_item_additional", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_order_item_additional_values", "unit_price >= 0 and quantity > 0");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Ordering.OrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("new_status");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("previous_status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EstablishmentId", "OrderId", "OccurredAt");

                    b.ToTable("order_status_history", "orders");
                });

            modelBuilder.Entity("OrderHub.Domain.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<decimal>("Change")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("change");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("PaymentMethodCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("payment_method_code");

                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_method_id");

                    b.Property<string>("PaymentMethodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("payment_method_name");

                    b.Property<decimal?>("ReceivedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("received_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EstablishmentId", "PaymentMethodId");

                    b.HasIndex("TenantId", "EstablishmentId", "OrderId", "Status");

                    b.ToTable("payment", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_payment_amounts", "amount > 0 and (received_amount is null or received_amount >= amount) and change >= 0");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Payments.PaymentIdempotency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_hash");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EstablishmentId", "Key")
                        .IsUnique();

                    b.HasIndex("TenantId", "EstablishmentId", "PaymentId");

                    b.ToTable("payment_idempotency", "payments");
                });

            modelBuilder.Entity("OrderHub.Domain.Payments.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowsChange")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_change");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EstablishmentId", "Code")
                        .IsUnique();

                    b.ToTable("payment_method", "payments");
                });

            modelBuilder.Entity("OrderHub.Domain.Promotions.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("discount_type");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("MaximumUses")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_uses");

                    b.Property<decimal>("MinimumOrder")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("minimum_order");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer")
                        .HasColumnName("used_count");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("value");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EstablishmentId", "Code")
                        .IsUnique();

                    b.ToTable("coupon", "promotions", t =>
                        {
                            t.HasCheckConstraint("ck_coupon_uses", "used_count >= 0 and (maximum_uses is null or (maximum_uses > 0 and used_count <= maximum_uses))");

                            t.HasCheckConstraint("ck_coupon_value", "value > 0 and (discount_type <> 'Percentage' or value <= 100)");

                            t.HasCheckConstraint("ck_coupon_window", "starts_at < ends_at");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Promotions.CouponUse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("uuid")
                        .HasColumnName("coupon_id");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discount");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EstablishmentId", "OrderId");

                    b.HasIndex("TenantId", "EstablishmentId", "CouponId", "OrderId")
                        .IsUnique();

                    b.ToTable("coupon_use", "promotions", t =>
                        {
                            t.HasCheckConstraint("ck_coupon_use_discount", "discount >= 0");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Tenancy.Establishment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("trade_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_establishment");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_establishment_slug");

                    b.HasIndex("TenantId");

                    b.ToTable("establishment", "tenancy");
                });

            modelBuilder.Entity("OrderHub.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.ToTable("tenant", "tenancy");
                });

            modelBuilder.Entity("OrderHub.Infrastructure.Persistence.Write.Configurations.AdministrativeRoleDefinition", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("administrative_role", "identity");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "OWNER",
                            Name = "Owner"
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "ADMIN",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "MANAGER",
                            Name = "Manager"
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "ATTENDANT",
                            Name = "Attendant"
                        },
                        new
                        {
                            Id = (short)5,
                            Code = "KITCHEN",
                            Name = "Kitchen"
                        },
                        new
                        {
                            Id = (short)6,
                            Code = "DELIVERY",
                            Name = "Delivery"
                        });
                });

            modelBuilder.Entity("OrderHub.Infrastructure.Persistence.Write.Configurations.OrderNumberCounter", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<long>("LastNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_number");

                    b.HasKey("TenantId", "EstablishmentId");

                    b.ToTable("order_number_counter", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_order_number_counter", "last_number > 0");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.Additional", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Establishment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.AdditionalGroup", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Establishment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.AdditionalGroupItem", b =>
                {
                    b.HasOne("OrderHub.Domain.Catalog.Additional", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId", "AdditionalId")
                        .HasPrincipalKey("TenantId", "EstablishmentId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderHub.Domain.Catalog.AdditionalGroup", null)
                        .WithMany("Items")
                        .HasForeignKey("TenantId", "EstablishmentId", "GroupId")
                        .HasPrincipalKey("TenantId", "EstablishmentId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.Category", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Establishment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderHub.Domain.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId", "ParentCategoryId")
                        .HasPrincipalKey("TenantId", "EstablishmentId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.Product", b =>
                {
                    b.HasOne("OrderHub.Domain.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId", "CategoryId")
                        .HasPrincipalKey("TenantId", "EstablishmentId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.ProductAdditionalGroup", b =>
                {
                    b.HasOne("OrderHub.Domain.Catalog.AdditionalGroup", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId", "GroupId")
                        .HasPrincipalKey("TenantId", "EstablishmentId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderHub.Domain.Catalog.Product", null)
                        .WithMany("AdditionalGroups")
                        .HasForeignKey("TenantId", "EstablishmentId", "ProductId")
                        .HasPrincipalKey("TenantId", "EstablishmentId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.ProductImage", b =>
                {
                    b.HasOne("OrderHub.Domain.Catalog.Product", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.ProductVariation", b =>
                {
                    b.HasOne("OrderHub.Domain.Catalog.Product", null)
                        .WithMany("Variations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Customers.Customer", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Establishment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Customers.CustomerAddress", b =>
                {
                    b.HasOne("OrderHub.Domain.Customers.Customer", null)
                        .WithMany("Addresses")
                        .HasForeignKey("TenantId", "EstablishmentId", "CustomerId")
                        .HasPrincipalKey("TenantId", "EstablishmentId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Identity.AdministrativeUser", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("OrderHub.Domain.Identity.AdministrativeUserRole", "RoleMemberships", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<short>("Role")
                                .HasColumnType("smallint")
                                .HasColumnName("role_id");

                            b1.HasKey("UserId", "Role");

                            b1.HasIndex("Role");

                            b1.ToTable("administrative_user_role", "identity");

                            b1.HasOne("OrderHub.Infrastructure.Persistence.Write.Configurations.AdministrativeRoleDefinition", null)
                                .WithMany()
                                .HasForeignKey("Role")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("OrderHub.Domain.Identity.UserEstablishmentAccess", "EstablishmentAccesses", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<Guid>("EstablishmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("establishment_id");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean")
                                .HasColumnName("is_active");

                            b1.Property<DateTimeOffset?>("RevokedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("revoked_at");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.HasKey("UserId", "EstablishmentId");

                            b1.HasIndex("TenantId", "EstablishmentId");

                            b1.HasIndex("TenantId", "UserId");

                            b1.ToTable("user_establishment_access", "identity");

                            b1.HasOne("OrderHub.Domain.Tenancy.Establishment", null)
                                .WithMany()
                                .HasForeignKey("TenantId", "EstablishmentId")
                                .HasPrincipalKey("TenantId", "Id")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("TenantId", "UserId")
                                .HasPrincipalKey("TenantId", "Id");
                        });

                    b.Navigation("EstablishmentAccesses");

                    b.Navigation("RoleMemberships");
                });

            modelBuilder.Entity("OrderHub.Domain.Operations.BusinessHours", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Establishment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Operations.ServiceTable", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Establishment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Ordering.Order", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Establishment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderHub.Domain.Promotions.Coupon", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId", "CouponId")
                        .HasPrincipalKey("TenantId", "EstablishmentId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("OrderHub.Domain.Ordering.DeliveryAddressSnapshot", "DeliveryAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("delivery_city");

                            b1.Property<string>("Complement")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("delivery_complement");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("delivery_neighborhood");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("delivery_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)")
                                .HasColumnName("delivery_postal_code");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("delivery_state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("delivery_street");

                            b1.HasKey("OrderId");

                            b1.ToTable("order", "orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("DeliveryAddress");
                });

            modelBuilder.Entity("OrderHub.Domain.Ordering.OrderItem", b =>
                {
                    b.HasOne("OrderHub.Domain.Ordering.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("TenantId", "EstablishmentId", "OrderId")
                        .HasPrincipalKey("TenantId", "EstablishmentId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Ordering.OrderItemAdditional", b =>
                {
                    b.HasOne("OrderHub.Domain.Ordering.OrderItem", null)
                        .WithMany("Additionals")
                        .HasForeignKey("TenantId", "EstablishmentId", "OrderItemId")
                        .HasPrincipalKey("TenantId", "EstablishmentId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Ordering.OrderStatusHistory", b =>
                {
                    b.HasOne("OrderHub.Domain.Ordering.Order", null)
                        .WithMany("History")
                        .HasForeignKey("TenantId", "EstablishmentId", "OrderId")
                        .HasPrincipalKey("TenantId", "EstablishmentId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Payments.Payment", b =>
                {
                    b.HasOne("OrderHub.Domain.Ordering.Order", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId", "OrderId")
                        .HasPrincipalKey("TenantId", "EstablishmentId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderHub.Domain.Payments.PaymentMethod", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId", "PaymentMethodId")
                        .HasPrincipalKey("TenantId", "EstablishmentId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Payments.PaymentIdempotency", b =>
                {
                    b.HasOne("OrderHub.Domain.Payments.Payment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId", "PaymentId")
                        .HasPrincipalKey("TenantId", "EstablishmentId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Payments.PaymentMethod", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Establishment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Promotions.Coupon", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Establishment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Promotions.CouponUse", b =>
                {
                    b.HasOne("OrderHub.Domain.Promotions.Coupon", null)
                        .WithMany("Uses")
                        .HasForeignKey("TenantId", "EstablishmentId", "CouponId")
                        .HasPrincipalKey("TenantId", "EstablishmentId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderHub.Domain.Ordering.Order", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId", "OrderId")
                        .HasPrincipalKey("TenantId", "EstablishmentId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Tenancy.Establishment", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("OrderHub.Domain.Tenancy.EstablishmentTheme", "Theme", b1 =>
                        {
                            b1.Property<Guid>("establishment_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("BackgroundColor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("background_color");

                            b1.Property<string>("FaviconUrl")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("favicon_url");

                            b1.Property<string>("FontFamily")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("font_family");

                            b1.Property<string>("LogoUrl")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("logo_url");

                            b1.Property<string>("PrimaryColor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("primary_color");

                            b1.Property<string>("SecondaryColor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("secondary_color");

                            b1.Property<string>("TextColor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("text_color");

                            b1.HasKey("establishment_id");

                            b1.ToTable("establishment_theme", "tenancy");

                            b1.WithOwner()
                                .HasForeignKey("establishment_id");
                        });

                    b.Navigation("Theme")
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Infrastructure.Persistence.Write.Configurations.OrderNumberCounter", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Establishment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.AdditionalGroup", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.Product", b =>
                {
                    b.Navigation("AdditionalGroups");

                    b.Navigation("Images");

                    b.Navigation("Variations");
                });

            modelBuilder.Entity("OrderHub.Domain.Customers.Customer", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("OrderHub.Domain.Ordering.Order", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("OrderHub.Domain.Ordering.OrderItem", b =>
                {
                    b.Navigation("Additionals");
                });

            modelBuilder.Entity("OrderHub.Domain.Promotions.Coupon", b =>
                {
                    b.Navigation("Uses");
                });
#pragma warning restore 612, 618
        }
    }
}
