// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderHub.Infrastructure.Persistence.Write;

#nullable disable

namespace OrderHub.Infrastructure.Migrations.Migrations
{
    [DbContext(typeof(OrderHubDbContext))]
    [Migration("20260820135644_ProductCatalog")]
    partial class ProductCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderHub.Domain.Catalog.Additional", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EstablishmentId", "Name");

                    b.ToTable("additional", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_additional_price", "price >= 0");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.AdditionalGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MaximumSelection")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_selection");

                    b.Property<int>("MinimumSelection")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_selection");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EstablishmentId", "Name");

                    b.ToTable("additional_group", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_additional_group_maximum", "maximum_selection >= 1");

                            t.HasCheckConstraint("ck_additional_group_minimum", "minimum_selection >= 0");

                            t.HasCheckConstraint("ck_additional_group_range", "minimum_selection <= maximum_selection");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.AdditionalGroupItem", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("AdditionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("additional_id");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("GroupId", "AdditionalId");

                    b.HasIndex("GroupId", "Order");

                    b.HasIndex("TenantId", "EstablishmentId", "AdditionalId");

                    b.HasIndex("TenantId", "EstablishmentId", "GroupId");

                    b.ToTable("additional_group_item", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_additional_group_item_order", "\"order\" >= 0");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EstablishmentId", "ParentCategoryId", "Order");

                    b.ToTable("category", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_category_order", "\"order\" >= 0");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowsNotes")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_notes");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("base_price");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "EstablishmentId", "CategoryId");

                    b.HasIndex("TenantId", "EstablishmentId", "Code")
                        .IsUnique();

                    b.ToTable("product", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_product_base_price", "base_price >= 0");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.ProductAdditionalGroup", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("ProductId", "GroupId");

                    b.HasIndex("ProductId", "Order");

                    b.HasIndex("TenantId", "EstablishmentId", "GroupId");

                    b.HasIndex("TenantId", "EstablishmentId", "ProductId");

                    b.ToTable("product_additional_group", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_product_additional_group_order", "\"order\" >= 0");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_principal");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasFilter("is_principal");

                    b.HasIndex("ProductId", "Order");

                    b.ToTable("product_image", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_product_image_order", "\"order\" >= 0");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.ProductVariation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Order");

                    b.ToTable("product_variation", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_product_variation_order", "\"order\" >= 0");

                            t.HasCheckConstraint("ck_product_variation_price", "price >= 0");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Identity.AdministrativeUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastAccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_access_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_administrative_user_tenant_email");

                    b.ToTable("administrative_user", "identity");
                });

            modelBuilder.Entity("OrderHub.Domain.Operations.BusinessHours", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly>("ClosesAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("closes_at");

                    b.Property<short>("DayOfWeek")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_week");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<TimeOnly>("OpensAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("opens_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("EstablishmentId", "DayOfWeek");

                    b.HasIndex("TenantId", "EstablishmentId");

                    b.ToTable("business_hours", "operations", t =>
                        {
                            t.HasCheckConstraint("ck_business_hours_interval", "closes_at > opens_at");
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Operations.ServiceTable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("QrCodeToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("qr_code_token");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("QrCodeToken")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("EstablishmentId", "Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "EstablishmentId");

                    b.ToTable("service_table", "operations");
                });

            modelBuilder.Entity("OrderHub.Domain.Tenancy.Establishment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("trade_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_establishment");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_establishment_slug");

                    b.HasIndex("TenantId");

                    b.ToTable("establishment", "tenancy");
                });

            modelBuilder.Entity("OrderHub.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.ToTable("tenant", "tenancy");
                });

            modelBuilder.Entity("OrderHub.Infrastructure.Persistence.Write.Configurations.AdministrativeRoleDefinition", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("administrative_role", "identity");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "OWNER",
                            Name = "Owner"
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "ADMIN",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "MANAGER",
                            Name = "Manager"
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "ATTENDANT",
                            Name = "Attendant"
                        },
                        new
                        {
                            Id = (short)5,
                            Code = "KITCHEN",
                            Name = "Kitchen"
                        },
                        new
                        {
                            Id = (short)6,
                            Code = "DELIVERY",
                            Name = "Delivery"
                        });
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.Additional", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Establishment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.AdditionalGroup", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Establishment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.AdditionalGroupItem", b =>
                {
                    b.HasOne("OrderHub.Domain.Catalog.Additional", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId", "AdditionalId")
                        .HasPrincipalKey("TenantId", "EstablishmentId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderHub.Domain.Catalog.AdditionalGroup", null)
                        .WithMany("Items")
                        .HasForeignKey("TenantId", "EstablishmentId", "GroupId")
                        .HasPrincipalKey("TenantId", "EstablishmentId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.Category", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Establishment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderHub.Domain.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId", "ParentCategoryId")
                        .HasPrincipalKey("TenantId", "EstablishmentId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.Product", b =>
                {
                    b.HasOne("OrderHub.Domain.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId", "CategoryId")
                        .HasPrincipalKey("TenantId", "EstablishmentId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.ProductAdditionalGroup", b =>
                {
                    b.HasOne("OrderHub.Domain.Catalog.AdditionalGroup", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId", "GroupId")
                        .HasPrincipalKey("TenantId", "EstablishmentId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderHub.Domain.Catalog.Product", null)
                        .WithMany("AdditionalGroups")
                        .HasForeignKey("TenantId", "EstablishmentId", "ProductId")
                        .HasPrincipalKey("TenantId", "EstablishmentId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.ProductImage", b =>
                {
                    b.HasOne("OrderHub.Domain.Catalog.Product", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.ProductVariation", b =>
                {
                    b.HasOne("OrderHub.Domain.Catalog.Product", null)
                        .WithMany("Variations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Identity.AdministrativeUser", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("OrderHub.Domain.Identity.AdministrativeUserRole", "RoleMemberships", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<short>("Role")
                                .HasColumnType("smallint")
                                .HasColumnName("role_id");

                            b1.HasKey("UserId", "Role");

                            b1.HasIndex("Role");

                            b1.ToTable("administrative_user_role", "identity");

                            b1.HasOne("OrderHub.Infrastructure.Persistence.Write.Configurations.AdministrativeRoleDefinition", null)
                                .WithMany()
                                .HasForeignKey("Role")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("OrderHub.Domain.Identity.UserEstablishmentAccess", "EstablishmentAccesses", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<Guid>("EstablishmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("establishment_id");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean")
                                .HasColumnName("is_active");

                            b1.Property<DateTimeOffset?>("RevokedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("revoked_at");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.HasKey("UserId", "EstablishmentId");

                            b1.HasIndex("TenantId", "EstablishmentId");

                            b1.HasIndex("TenantId", "UserId");

                            b1.ToTable("user_establishment_access", "identity");

                            b1.HasOne("OrderHub.Domain.Tenancy.Establishment", null)
                                .WithMany()
                                .HasForeignKey("TenantId", "EstablishmentId")
                                .HasPrincipalKey("TenantId", "Id")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("TenantId", "UserId")
                                .HasPrincipalKey("TenantId", "Id");
                        });

                    b.Navigation("EstablishmentAccesses");

                    b.Navigation("RoleMemberships");
                });

            modelBuilder.Entity("OrderHub.Domain.Operations.BusinessHours", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Establishment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Operations.ServiceTable", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Establishment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EstablishmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Tenancy.Establishment", b =>
                {
                    b.HasOne("OrderHub.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("OrderHub.Domain.Tenancy.EstablishmentTheme", "Theme", b1 =>
                        {
                            b1.Property<Guid>("establishment_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("BackgroundColor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("background_color");

                            b1.Property<string>("FaviconUrl")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("favicon_url");

                            b1.Property<string>("FontFamily")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("font_family");

                            b1.Property<string>("LogoUrl")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("logo_url");

                            b1.Property<string>("PrimaryColor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("primary_color");

                            b1.Property<string>("SecondaryColor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("secondary_color");

                            b1.Property<string>("TextColor")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("text_color");

                            b1.HasKey("establishment_id");

                            b1.ToTable("establishment_theme", "tenancy");

                            b1.WithOwner()
                                .HasForeignKey("establishment_id");
                        });

                    b.Navigation("Theme")
                        .IsRequired();
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.AdditionalGroup", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OrderHub.Domain.Catalog.Product", b =>
                {
                    b.Navigation("AdditionalGroups");

                    b.Navigation("Images");

                    b.Navigation("Variations");
                });
#pragma warning restore 612, 618
        }
    }
}
