using FluentValidation;
namespace OrderHub.Application.Payments;
public sealed class UpsertPaymentMethodCommandValidator : AbstractValidator<UpsertPaymentMethodCommand> { public UpsertPaymentMethodCommandValidator() { RuleFor(x => x.EstablishmentId).NotEmpty(); RuleFor(x => x.Code).NotEmpty().MaximumLength(30); RuleFor(x => x.Name).NotEmpty().MaximumLength(100); } }
public sealed class SetPaymentMethodActiveCommandValidator : AbstractValidator<SetPaymentMethodActiveCommand> { public SetPaymentMethodActiveCommandValidator() { RuleFor(x => x.EstablishmentId).NotEmpty(); RuleFor(x => x.PaymentMethodId).NotEmpty(); } }
public sealed class CreatePaymentCommandValidator : AbstractValidator<CreatePaymentCommand> { public CreatePaymentCommandValidator() { RuleFor(x => x.EstablishmentId).NotEmpty(); RuleFor(x => x.OrderId).NotEmpty(); RuleFor(x => x.PaymentMethodId).NotEmpty(); RuleFor(x => x.Amount).GreaterThan(0); RuleFor(x => x.ReceivedAmount).GreaterThan(0).When(x => x.ReceivedAmount.HasValue); } }
public sealed class ConfirmPaymentCommandValidator : AbstractValidator<ConfirmPaymentCommand> { public ConfirmPaymentCommandValidator() { RuleFor(x => x.EstablishmentId).NotEmpty(); RuleFor(x => x.PaymentId).NotEmpty(); RuleFor(x => x.Amount).GreaterThan(0); RuleFor(x => x.IdempotencyKey).NotEmpty().MinimumLength(8).MaximumLength(100); RuleFor(x => x.ExternalId).MaximumLength(100); } }
public sealed class FailPaymentCommandValidator : AbstractValidator<FailPaymentCommand> { public FailPaymentCommandValidator() { RuleFor(x => x.EstablishmentId).NotEmpty(); RuleFor(x => x.PaymentId).NotEmpty(); } }
public sealed class CancelPaymentCommandValidator : AbstractValidator<CancelPaymentCommand> { public CancelPaymentCommandValidator() { RuleFor(x => x.EstablishmentId).NotEmpty(); RuleFor(x => x.PaymentId).NotEmpty(); } }
public sealed class ListPaymentMethodsQueryValidator : AbstractValidator<ListPaymentMethodsQuery> { public ListPaymentMethodsQueryValidator() { RuleFor(x => x.EstablishmentId).NotEmpty(); } }
public sealed class GetOrderPaymentsQueryValidator : AbstractValidator<GetOrderPaymentsQuery> { public GetOrderPaymentsQueryValidator() { RuleFor(x => x.EstablishmentId).NotEmpty(); RuleFor(x => x.OrderId).NotEmpty(); } }
public sealed class SearchPaymentMethodsQueryValidator:AbstractValidator<SearchPaymentMethodsQuery>{public SearchPaymentMethodsQueryValidator(){RuleFor(x=>x.EstablishmentId).NotEmpty();RuleFor(x=>x.Search).MaximumLength(100);RuleFor(x=>x.Page).GreaterThan(0);RuleFor(x=>x.PageSize).InclusiveBetween(1,100);}}
